name = "PokerBots"
uuid = "3d0ee4cc-63eb-4b45-83bf-872522afc678"
authors = ["Charles Kawczynski <kawczynski.charles@gmail.com>"]
version = "0.1.0"

[deps]
PlayingCards = "ecfe714a-bcc2-4d11-ad00-25525ff8f984"
PokerHandEvaluator = "18ed25b1-892a-4a3b-b8fc-1036dc9a6a89"
TexasHoldem = "6cef90fc-eb55-4a2a-97d0-7ecce2b738fe"

[compat]
PlayingCards = "0.3.0"
PokerHandEvaluator = "0.2.4"
TexasHoldem = "0.1.0"
julia = "1.5.4"
